# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env'
end
  desc "Description of what the lane does"
  lane :build do
    build_ios_app
  end
  desc "Description of what the lane does"
  lane :deploy do
    pilot(api_key:  app_store_connect_api_key )
  end
end
